### ISSUE TITLE
Infinite Carry breaks cooked fish/meat

### ISSUE THREAD

**Issue by LetMeGitDat** [Xpazeman/tld-weight-tweaks#8]
With infinite carry on, cooking fish/meat results in 0 calorie cooked item. If you then eat the 0 calorie food item, your current WT becomes "NaN"/<whatever max wt is>and you can no longer move. 

Reloading game with infinite carry off will produce regular cooked items with calories.

**Comment by LetMeGitDat** [comment]
After a tiny bit more testing, I suspect the game is using raw fish wt to calculate cooked fish wt and calories. I suspect that the code for -35% wt reduction from cooking fish does not have safeguards for 0 wt fish.

**Comment by Geekerandy** [comment]
I can now confirm with the newest update to WeightTweaks, that this issue has been fixed.

**Comment by LetMeGitDat** [comment]
> I can now confirm with the newest update to WeightTweaks, that this issue has been fixed.

Yes the cooked food seems to work now, even the noodles mod but cooked fat ---> tallow from the candlelight mod is still having the issues. Perhaps because it's a material and not food.

**Comment by Xpazeman** [comment]
This was the result of the new way to modify weights, which wasn't ideal. I rolled back the system to what it was before, that while it introduces stuttering to some users, it works and doesn't break any of the mechanics.

To modify carry weight, I released an independent mod so for anyone that just wants to carry more they don't have to suffer the stuttering.
